default_language_version:
  python: python3.12

repos:
  # Black
  - repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
      - id: black
        types: [ python ]
        args: [ --check ]

  # isort
  - repo: local
    hooks:
        - id: isort
          name: isort
          entry: isort
          language: system
          types: [ python ]
          args: [ --check,--profile=black ]

  # flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: flake8

  # mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        types: [ python ]
        args: [ --strict ]